Support for transparent pixels
Artemis21/dpypx pull request #6
Opened 2021-06-11 10:33 UTC by Znunu

### Description
Transparent pixels in the image will not be drawn. Semi transparent pixels will be rounded to either fully transparent or opaque, because I wasn't exactly sure what to do with semi transparent pixels. I could technically draw a semi transparent pixel by looking at the previous pixel, but that would make draw_and_fix go forever since there isn't really a clear stop condition.

### Implementation
The grid in AutoDrawer used be a 2D array of Pixels. I modified it to be an 2D array of tuples, each tuple containing a pixel and a boolean value. The boolean determines if the pixel is transparent or not i.e. if it's going to be drawn. 

### Test
I tested it with a few .pngs at scale=1 and it seems to work fine

2021-06-11 17:12 UTC, Artemis21 requested changes
Minor issues, looks good though.

2021-06-11 17:12 UTC, Artemis21 commented on dpypx/autodraw.py
> -        """Draw from the pixels of an image."""
Why remove the docstring?

2021-06-11 17:12 UTC, Artemis21 commented on dpypx/autodraw.py
> +            image: Image.Image, scale: float = 1, strict: bool = False) -> AutoDrawer:
You added the `strict` param but don't seem to have used it...

2021-06-11 17:12 UTC, Artemis21 commented on dpypx/autodraw.py
> +        if not pixel[1]:
```suggestion
        colour, opaque = self.grid[y - self.y0][x - self.x0]
        if not opaque:
```
Using iterable unpacking for shorter code and better readability.

2021-06-11 17:12 UTC, Artemis21 commented on dpypx/autodraw.py
> +            [(Pixel(*pixel[:3]), bool(round(pixel[3] / 255))) for pixel in data[start:start + width]]
```suggestion
            [(Pixel(*pixel[:3]), pixel[3] > 127) for pixel in data[start:start + width]]
```
Equivalent code, less computation and simpler.

2021-06-11 17:14 UTC, Artemis21 commented on dpypx/autodraw.py
> +            [(Pixel(*pixel[:3]), bool(round(pixel[3] / 255))) for pixel in data[start:start + width]]
Even so actually this line is longer than ideal. Perhaps
```suggestion
            [
                (Pixel(*pixel[:3]), bool(round(pixel[3] / 255)))
                for pixel in data[start:start + width]
            ]
```

2021-06-12 00:39 UTC, Znunu commented
Thanks. Your suggestions were nice. Think I got them all.

2021-06-12 00:46 UTC, Artemis21 requested changes
Just one more thing

2021-06-12 00:46 UTC, Artemis21 commented on dpypx/autodraw.py
> +                row.append((Pixel.from_hex(lines.pop(0))), True)
```suggestion
                row.append((Pixel.from_hex(lines.pop(0)), True))
```
I think the brackets are slightly misplaced here.

2021-06-12 00:46 UTC, Artemis21 commented on dpypx/autodraw.py
> +            [(Pixel(*pixel[:3]), pixel[3] > 127) for pixel in data[start:start + width]]
This line is 88 lines long but the repo tries to keep lines under 80 (I mentioned this when making the suggestion)

2021-06-12 00:46 UTC, Artemis21 commented on dpypx/autodraw.py
> +	    if not opaque:
```suggestion
        colour, opaque = self.grid[y - self.y0][x - self.x0]
	  if not opaque:
```
Indentation

2021-06-12 16:46 UTC, Artemis21 requested changes

2021-06-12 16:46 UTC, Artemis21 commented on dpypx/autodraw.py
> +            [(Pixel(*pixel[:3]), pixel[3] > 127) for pixel in data[start:start + width]]
```suggestion
            [
                (Pixel(*pixel[:3]), pixel[3] > 127)
                for pixel in data[start:start + width]
            ]
```
Line length

2021-06-12 16:47 UTC, merged